# Generated by Django 2.2.4 on 2019-09-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190825_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_edit_aurhor', 'Create, update and delete authors'),)},
        ),
    ]
